server:
  log_level: info

otelcol.receiver.otlp "default" {
  grpc {
    endpoint = "0.0.0.0:4317"
  }

  http {
    endpoint = "0.0.0.0:4318"
  }

  output {
    traces  = [otelcol.processor.batch.default.input]
  }
}

otelcol.processor.batch "default" {
  output {
    traces  = [otelcol.exporter.logging.default.input]
  }
}

otelcol.exporter.logging "default" {
  verbosity           = "detailed"
  sampling_initial    = 5
  sampling_thereafter = 200
}
